apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-scheduler-prometheus-discovery
  name: kube-scheduler-prometheus-discovery
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.0.0.200
  ports:
  - name: https-metrics
    port: 10259
    protocol: TCP
